name: Cypress Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  # runs tests every day at 4am
  - cron: '0 4 * * 2,4,6'

jobs:
  cross-browser-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, electron, chromium ]
    name: Cypress tests using ${{ matrix.browser }} browser
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress test run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          headless: true
          env: configFile=int


  edge-test:
    runs-on: windows-latest
    # let's make sure our tests pass on Edge browser and report gets published
    name: Cypress tests using edge browser
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress tests on edge
        uses: cypress-io/github-action@v2
        with:
          browser: edge
          env: configFile=int
      - name: Cypress report generation 
        run: node cucumber-html-report.js
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
