name: E2E on Chrome
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
  # runs tests every day at 4am
  - cron: '0 4 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, electron, chromium ]
    # let's make sure our tests pass on Chrome browser
    name: ChromeTests on 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress test run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          headless: true
          env: configFile=int
      - name: Cypress report generation 
        run: node custom-reporter.js